spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mlakshmi2608@gmail.com
spring.mail.password=ygps ppjz bkeq oeyf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true